version: "3.9"
name: sysclim
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8123:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=sysclim
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5123:5432"
    restart: unless-stopped