# Generated by Django 4.2.11 on 2024-04-05 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0008_alter_atestado_dh_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exame',
            name='medico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='medicina.medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atestado',
            name='dh_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 14, 38, 55, 988841)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dh_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 14, 38, 55, 988159), verbose_name='Data e Hora de Realização'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='dh_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 14, 38, 55, 988440)),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='dh_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 14, 38, 55, 988655)),
        ),
        migrations.AlterModelTable(
            name='atestado',
            table='atestado',
        ),
        migrations.AlterModelTable(
            name='consulta',
            table='consulta',
        ),
        migrations.AlterModelTable(
            name='exame',
            table='exame',
        ),
        migrations.AlterModelTable(
            name='medico',
            table='medico',
        ),
        migrations.AlterModelTable(
            name='prontuario',
            table='prontuario',
        ),
    ]
