# Generated by Django 4.2.11 on 2024-04-06 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0010_alter_atestado_dh_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('perdida', 'Perdida')], default='agendada', max_length=50),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='dh_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 22, 23, 32, 319118)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dh_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 22, 23, 32, 318439), verbose_name='Data e Hora de Realização'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='dh_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 22, 23, 32, 318735)),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='dh_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 22, 23, 32, 318943)),
        ),
    ]
