# Generated by Django 4.2.11 on 2024-04-06 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0004_alter_vacina_dt_cadastro'),
        ('medicina', '0015_alter_atestado_dh_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='medico',
        ),
        migrations.AddField(
            model_name='prontuario',
            name='atestados',
            field=models.ManyToManyField(to='medicina.atestado'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='vacinas',
            field=models.ManyToManyField(to='enfermagem.vacina'),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='dh_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 12, 57, 387603)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dh_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 12, 57, 385825), verbose_name='Data e Hora de Realização'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='dh_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 12, 57, 386116)),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='dh_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 12, 57, 386326)),
        ),
    ]
