# Generated by Django 4.2.11 on 2024-04-06 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicina', '0016_remove_prontuario_medico_prontuario_atestados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='atestados',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='vacinas',
        ),
        migrations.AlterField(
            model_name='atestado',
            name='dh_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 31, 54, 408261)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dh_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 31, 54, 407062), verbose_name='Data e Hora de Realização'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='dh_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 31, 54, 407328)),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='dh_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 31, 54, 407554)),
        ),
    ]
