# Generated by Django 4.2.11 on 2024-04-06 01:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_paciente_created_by'),
        ('enfermagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('lote', models.CharField(max_length=24)),
                ('dt_cadastro', models.DateTimeField(default=datetime.datetime(2024, 4, 5, 22, 23, 32, 322742), null=True)),
                ('descricao', models.TextField()),
                ('enfermeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enfermagem.enfermeiro')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.paciente')),
            ],
            options={
                'db_table': 'vacina',
            },
        ),
    ]
