# Generated by Django 4.2.11 on 2024-04-06 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0002_vacina'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='dt_fabricacao',
            field=models.DateField(default='1999-09-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacina',
            name='dt_validade',
            field=models.DateField(default='2030-09-09'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacina',
            name='dt_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 1, 36, 26, 774737), null=True),
        ),
    ]
