# Generated by Django 4.2.11 on 2024-04-06 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0003_vacina_dt_fabricacao_vacina_dt_validade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='dt_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 12, 57, 385386), null=True),
        ),
    ]
