# Generated by Django 4.2.11 on 2024-04-06 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0004_alter_vacina_dt_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='dh_aplicacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='dt_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 31, 54, 406642), null=True),
        ),
    ]
