# Generated by Django 4.2.11 on 2024-04-07 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0005_vacina_dh_aplicacao_alter_vacina_dt_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='dt_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 0, 41, 7, 804361), null=True),
        ),
    ]
