# Generated by Django 4.2.11 on 2024-04-07 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermagem', '0006_alter_vacina_dt_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='dt_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 2, 27, 55, 511689), null=True),
        ),
    ]
