# Generated by Django 4.2.11 on 2024-03-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=64)),
                ('bairro', models.CharField(max_length=64)),
                ('numero', models.CharField(null=True)),
                ('complemento', models.CharField(null=True)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=24)),
                ('cep', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_final', models.DateField()),
                ('hr_inicio', models.TimeField()),
                ('hr_final', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('tuss', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('disponivel', models.BooleanField(default=True)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=64)),
                ('genero', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('dt_nascimento', models.DateField()),
                ('cargo', models.CharField()),
                ('ativo', models.BooleanField(default=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.endereco')),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nome', models.CharField(max_length=64, unique=True)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('genero', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('dt_nascimento', models.DateField()),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='common.assistente')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('coren', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.profissionalsaude')),
            ],
        ),
    ]
