# Generated by Django 4.2.11 on 2024-04-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0002_assistente_email_assistente_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='profissionalsaude',
            table='profissional',
        ),
    ]
