# Generated by Django 4.2.11 on 2024-04-05 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_assistente_profissional_delete_enfermeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='common.endereco'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
