# Generated by Django 4.2.11 on 2024-04-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_paciente_endereco_alter_paciente_dt_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='disponivel',
            new_name='ativo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='created_by',
        ),
    ]
