# Generated by Django 4.2.11 on 2024-04-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_rename_disponivel_sala_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='especialidade',
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='endereco',
        ),
        migrations.AlterModelTable(
            name='escala',
            table='escala',
        ),
        migrations.AlterModelTable(
            name='especialidade',
            table='especialidade',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
        migrations.AlterModelTable(
            name='sala',
            table='sala',
        ),
    ]
