# Generated by Django 4.2.11 on 2024-04-05 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_sala_especialidade_alter_endereco_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='common.assistente'),
        ),
    ]
