# Generated by Django 4.2.11 on 2024-04-07 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_paciente_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='profissionais',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
